import { Variable } from "./var";
/**
 * Generates a Variable object containing an array filled with values generated by a provided function.
 *
 * This function creates an array of the specified length and populates it with values 
 * generated by calling the provided `value` function for each element.
 *
 * @param length - The desired length of the array.
 * @param value - A function that generates a value for each element in the array. 
 *                Defaults to a function that returns an empty string.
 * @returns A Variable object containing the generated array.
 * 
 * @example
 * // Generate an array of 5 random numbers.
 * const randomNumbers = randarr(5, () => Math.random());
 * console.log(randomNumbers.data); // Output: [0.123, 0.456, 0.789, 0.101, 0.314] (example)
 * 
 * @example
 * // Generate an array of 3 strings with the value "hello".
 * const helloArray = randarr(3, () => "hello");
 * console.log(helloArray.data); // Output: ["hello", "hello", "hello"]
 */
export const randarr = (length: number, value: any = () => "") => {
  let arr: any[] = [];
  for (let i = 0; i < length; i++) {
    arr.push(value());
  }
  return new Variable(arr,"any");
};
